FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN corepack enable && yarn install --immutable

COPY . .

RUN yarn build

EXPOSE 3000

# RUN yarn migrate:run

CMD ["yarn", "start:prod"]