FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache ffmpeg

COPY package.json ./
COPY yarn.lock ./
RUN corepack enable && yarn install --immutable

COPY . .

RUN yarn build

RUN yarn migrate:run

CMD ["yarn", "start:worker"]
